package errors

import "github.com/funnyecho/code-push/pkg/errors"

const (
	FA_INVALID_PARAMS = "FA_INVALID_PARAMS"

	FA_BRANCH_CAN_NOT_FOUND     = "FA_BRANCH_CAN_NOT_FOUND"
	FA_BRANCH_NAME_EXISTED      = "FA_BRANCH_NAME_EXISTED"
	FA_BRANCH_INVALID_ENC_TOKEN = "FA_BRANCH_INVALID_ENC_TOKEN"
	FA_BRANCH_SAVE_FAILED       = "FA_BRANCH_SAVE_FAILED"
	FA_BRANCH_DELETE_FAILED     = "FA_BRANCH_DELETE_FAILED"

	FA_ENV_NOT_FOUND         = "FA_ENV_NOT_FOUND"
	FA_ENV_CREATION_FAILED   = "FA_ENV_CREATION_FAILED"
	FA_ENV_INVALID_ENC_TOKEN = "FA_ENV_INVALID_ENC_TOKEN"
	FA_ENV_EXISTED           = "FA_ENV_EXISTED"
	FA_ENV_NAME_EXISTED      = "FA_ENV_NAME_EXISTED"
	FA_ENV_SAVE_FAILED       = "FA_ENV_SAVE_FAILED"
	FA_ENV_DELETE_FAILED     = "FA_ENV_DELETE_FAILED"

	FA_VERSION_OPERATION_FORBIDDEN = "FA_VERSION_OPERATION_FORBIDDEN"
	FA_VERSION_NOT_FOUND           = "FA_VERSION_NOT_FOUND"
	FA_VERSION_RELEASE_FAILED      = "FA_VERSION_RELEASE_FAILED"
	FA_VERSION_SAVE_FAILED         = "FA_VERSION_SAVE_FAILED"
)

type MetaFields = errors.MetaFields
